import ThemeRegistry from "@/components/ThemeResistry/ThemeResistry";
import "./globals.css";
import { Inter } from "next/font/google";
import CourseResistry from "@/components/CourseResistry/courseResistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className} style={{ height: "100vh" }}>
        <CourseResistry>
          <ThemeRegistry>{children}</ThemeRegistry>
        </CourseResistry>
      </body>
    </html>
  );
}
